spring.application.name=hogar-service

spring.datasource.url=jdbc:postgresql://dpg-d7rtr98g4nts73cvstgg-a.virginia-postgres.render.com:5432/tareas_domesticas_167w
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:643Ko5AzKXRCsH081x6jKrq5Bj3QKE6i}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.springframework.transaction=DEBUG